spring:
  config:
    import: optional:file:.env-dev[.properties]
  profiles:
    application:
      name: rolemanage
    # 多环境配置，命令行执行：java -jar XXX-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  error:
    include-message: always
  port: ${SERVER_PORT:8089}

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security.oauth2: DEBUG



